### ISSUE TITLE
returned non-zero exit status 1

### ISSUE THREAD

**Issue by autumn-moon-py** [worawit/blutter#46] opened 2024-02-22 05:24 UTC
```
D:\project\blutter>python -V
Python 3.11.4

D:\project\blutter>python scripts\init_env_win.py
Downloading ICU library from https://github.com/unicode-org/icu/releases/download/release-73-2/icu4c-73_2-Win64-MSVC2019.zip
Extracting ICU library
Downloading Capstone from https://github.com/capstone-engine/capstone/releases/download/4.0.2/capstone-4.0.2-win64.zip
Extracting Capstone library
Copying dlls to bin directory
Done

D:\project\blutter>python blutter.py
Dart version: 3.0.5, Snapshot: 90b56a561f70cd55e972cb49b79b3d8b, Target: android arm64
flags: product no-code_comments no-dwarf_stack_traces_mode no-lazy_dispatchers dedup_instructions no-asserts arm64 android compressed-pointers null-safety
CMake Error at C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Failed to find all ICU components (missing: ICU_INCLUDE_DIR ICU_LIBRARY
  _ICU_REQUIRED_LIBS_FOUND)
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  C:/Program Files/CMake/share/cmake-3.29/Modules/FindICU.cmake:334 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:20 (find_package)


-- Configuring incomplete, errors occurred!
Traceback (most recent call last):
  File "D:\project\blutter\blutter.py", line 250, in <module>
    main(input, outdir, rebuild, vs_sln, no_analysis)
  File "D:\project\blutter\blutter.py", line 169, in main
    fetch_and_build(
  File "D:\project\blutter\dartvm_fetch_build.py", line 120, in fetch_and_build
    cmake_dart(ver, arch, os_name, has_compressed_ptrs, outdir)
  File "D:\project\blutter\dartvm_fetch_build.py", line 110, in cmake_dart
    subprocess.run([CMAKE_CMD, '-GNinja', '-B', builddir, f'-DTARGET_OS={os_name}', f'-DTARGET_ARCH={arch}',
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\develop\miniconda\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['cmake', '-GNinja', '-B', 'D:\\project\\blutter\\build\\dartvm3.0.5_android_arm64', '-DTARGET_OS=android', '-DTARGET_ARCH=arm64', '-DCOMPRESSED_PTRS=1', '-DCMAKE_BUILD_TYPE=Release', '--log-level=NOTICE']' returned non-zero exit status 1.
```

**Comment by worawit** [comment] 2024-02-22 10:28
Duplicate of #45

**Closed by worawit** 2024-02-22 10:28 UTC

**Comment by autumn-moon-py** [comment] 2024-02-22 12:20
> Duplicate of #45

All the replies in this issue(#45) cannot explain this error ,there are too many and messy replies, so I am creating a new issue
